spring.application.name=RPR1

# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/RPR1Project
spring.datasource.username=root
spring.datasource.password=Password123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update